### PR TITLE
Updated Dockerfile Under Mysql

### PR DESCRIPTION
**Pull request by shashwat50**
Resolution for error : 'performance_schema.session_variables' doesn't exist".

### CODE REVIEW

**Comment by shashwat50** [comment]
Was getting error : "performance_schema.session_variables' doesn't exist" and Shephard container was not getting connected to mysql.
OS : Ubuntu 16.04.3 LTS

**Comment by ismisepaul** [comment]
Hi @shashwat50, first off thanks for the pull request. 

I just have a few questions so that I understand what's going on as I cannot reproduce the error you're having and I'm also using Ubuntu 16.04.

When I bring the environment up with docker-compose everything works as it should. I then checked my MySQL server;

```docker exec -it <container> /bin/bash```

```
mysql@4dd58201e6be:/$ cat /etc/mysql/my.cnf
[mysqld]
skip-host-cache
datadir = /var/lib/mysql
!includedir /etc/mysql/conf.d/`
```

```
mysql> show databases;
+--------------------------------+
| Database                       |
+--------------------------------+
| information_schema             |
| BrokenAuthAndSessMangChalFive  |
| BrokenAuthAndSessMangChalSeven |
| BrokenAuthAndSessMangChalSix   |
| BrokenAuthAndSessMangChalThree |
| BrokenAuthAndSessMangChalTwo   |
| CryptShop                      |
| SQLiC5Shop                     |
| SqlChalEmail                   |
| SqlChalFourSuperSecure         |
| SqlChalOne                     |
| SqlChalSix                     |
| SqlChalStoredProc              |
| SqlChalThree                   |
| SqlInjLesson                   |
| SqlPoorEscape                  |
| UrlAccessThree                 |
| backup                         |
| core                           |
| csrfChallengeEnumTokens        |
| csrfChallengeFour              |
| directObjectBank               |
| directObjectRefChalOne         |
| directObjectRefChalTwo         |
| mysql                          |
| performance_schema             |
| securityMisconfigStealToken    |
| sqlInjectSeven                 |
| sys                            |
+--------------------------------+
29 rows in set (0.01 sec)
```

```
mysql> use performance_schema;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+------------------------------------------------------+
| Tables_in_performance_schema                         |
+------------------------------------------------------+
| accounts                                             |
| cond_instances                                       |
| events_stages_current                                |
| events_stages_history                                |
| events_stages_history_long                           |
| events_stages_summary_by_account_by_event_name       |
| events_stages_summary_by_host_by_event_name          |
| events_stages_summary_by_thread_by_event_name        |
| events_stages_summary_by_user_by_event_name          |
| events_stages_summary_global_by_event_name           |
| events_statements_current                            |
| events_statements_history                            |
| events_statements_history_long                       |
| events_statements_summary_by_account_by_event_name   |
| events_statements_summary_by_digest                  |
| events_statements_summary_by_host_by_event_name      |
| events_statements_summary_by_program                 |
| events_statements_summary_by_thread_by_event_name    |
| events_statements_summary_by_user_by_event_name      |
| events_statements_summary_global_by_event_name       |
| events_transactions_current                          |
| events_transactions_history                          |
| events_transactions_history_long                     |
| events_transactions_summary_by_account_by_event_name |
| events_transactions_summary_by_host_by_event_name    |
| events_transactions_summary_by_thread_by_event_name  |
| events_transactions_summary_by_user_by_event_name    |
| events_transactions_summary_global_by_event_name     |
| events_waits_current                                 |
| events_waits_history                                 |
| events_waits_history_long                            |
| events_waits_summary_by_account_by_event_name        |
| events_waits_summary_by_host_by_event_name           |
| events_waits_summary_by_instance                     |
| events_waits_summary_by_thread_by_event_name         |
| events_waits_summary_by_user_by_event_name           |
| events_waits_summary_global_by_event_name            |
| file_instances                                       |
| file_summary_by_event_name                           |
| file_summary_by_instance                             |
| global_status                                        |
| global_variables                                     |
| host_cache                                           |
| hosts                                                |
| memory_summary_by_account_by_event_name              |
| memory_summary_by_host_by_event_name                 |
| memory_summary_by_thread_by_event_name               |
| memory_summary_by_user_by_event_name                 |
| memory_summary_global_by_event_name                  |
| metadata_locks                                       |
| mutex_instances                                      |
| objects_summary_global_by_type                       |
| performance_timers                                   |
| prepared_statements_instances                        |
| replication_applier_configuration                    |
| replication_applier_status                           |
| replication_applier_status_by_coordinator            |
| replication_applier_status_by_worker                 |
| replication_connection_configuration                 |
| replication_connection_status                        |
| replication_group_member_stats                       |
| replication_group_members                            |
| rwlock_instances                                     |
| session_account_connect_attrs                        |
| session_connect_attrs                                |
| session_status                                       |
| session_variables                                    |
| setup_actors                                         |
| setup_consumers                                      |
| setup_instruments                                    |
| setup_objects                                        |
| setup_timers                                         |
| socket_instances                                     |
| socket_summary_by_event_name                         |
| socket_summary_by_instance                           |
| status_by_account                                    |
| status_by_host                                       |
| status_by_thread                                     |
| status_by_user                                       |
| table_handles                                        |
| table_io_waits_summary_by_index_usage                |
| table_io_waits_summary_by_table                      |
| table_lock_waits_summary_by_table                    |
| threads                                              |
| user_variables_by_thread                             |
| users                                                |
| variables_by_thread                                  |
+------------------------------------------------------+
87 rows in set (0.00 sec)
```

So it seems like that table does exist. So I had a look at what ```show_compatibility_56 = ON``` [does ](https://dev.mysql.com/doc/refman/5.7/en/performance-schema-variable-table-migration.html) and it seems to turn on compatibility mode for MySQL 5.6. Since we initially had this app running on 5.5 and then upgraded to 5.7

https://github.com/OWASP/SecurityShepherd/commit/7619c48a7d92d491ce84d94b1965a03063e5627f#diff-f579cccc964135c7d644c7b2d3b0d3ec

I thought that might cause issues but I wasn't seeing any. 

Could I ask if you were running off a fresh instance of Security Shepherd or if you were using an older version of the db and upgrading or did you tweak the version of MySQL?

**Review by ismisepaul — COMMENTED** [review]
https://github.com/OWASP/SecurityShepherd/pull/512#issuecomment-554361001

**Comment by ismisepaul** [comment]
Closing, if you feel I was wrong in my assessment please reopen and we can discuss.

**Pull request closed without merging**
