### PR TITLE
Master

### PR DESCRIPTION
**Pull request by konduktodemo**

### CODE REVIEW

**Comment by markdenihan** [comment]
@mtesauro Can you change this to merge into dev instead of master?

**Comment by ismisepaul** [comment]
@konduktodemo what is the purpose of this pull request? We don't have access to Fortify nor do we use Jenkins to build Shepherd. This is too specific to you own project to be made part of the overall project.

Also you've published some secrets (tokens) that you shouldn't have on a public repo.

If you feel there is a need to have Jenkins config file on the public repo could you open an issue before making a pull request?

We can then look into reopening this pull request.

**Comment by konduktodemo** [comment]
Hello,

I think I made a mistake. My goal was just to fork the repo and work on the
jenkins pipeline. I must have sent the pull request by mistake. How can I
fix this error. Can you help me?

Thank you.
Davuthan Yaman
System Support Manager

T: +90 216 504 15 00
M: +90 537 500 22 55
davuthan@endpoint-labs.com
www.endpoint-labs.com
Sanayi Mahallesi Teknopark Bulvari No:1/4A No:412 Pendik / Istanbul /
TURKIYE
[image: LinkedIn icon]
<https://www.linkedin.com/in/davuthan-yaman-185b0b65/>

Bu e-posta'nin icerdigi bilgiler, ekleri de dahil olmak uzere KISIYE ÖZEL
ve hukuken gizlidir. Bu mesajin gonderilmek istendigi kisi degilseniz ya da
bu e-posta'yi yanlislikla aldiysaniz, lutfen yollayan kisiyi haberdar
ediniz ve mesaji bilgisayarinizdan siliniz. Mesajin iceriginden,
iletilmesinden, alinmasindan, saklanmasindan, gizliliginin korunamamasindan
ve dogacak baska herhangi bir sonuctan Endpoint Bilgi Teknolojileri
Güvenliği Ar-Ge A.Ş. ve istirakleri sorumlu tutulamaz.

This e-mail message including any attachment is confidential for
the intended recipient and legally privileged. If you are not the
intended recipient or you received this e-mail in error kindly notify the
sender and delete this message from your computer. Endpoint Bilgi
Teknolojileri Güvenliği Ar-Ge A.Ş. and subsidiaries shall have no liability
with regard to the information contained in the message, its transmission,
reception, storage, preservation of confidentiality and any other
consequences.


Pól <notifications@github.com>, 7 Şub 2020 Cum, 19:23 tarihinde şunu yazdı:

**Comment by ismisepaul** [comment]
Hi @konduktodemo don't worry I've closed the pull request so it's fine.

The only thing I would advise is to keep your secrets secret and not publish the keys on your own repo either.

**Comment by konduktodemo** [comment]
Hello Pól,

Thank you so much for your advice. There is no problem in knowing the
tokens we share. Because it is a local service. The only thing I didn't
know about this was that public repo was not privately forked. I thought it
was like this.

Thank you and have nice work.

Davuthan Yaman
System Support Manager

T: +90 216 504 15 00
M: +90 537 500 22 55
davuthan@endpoint-labs.com
www.endpoint-labs.com
Sanayi Mahallesi Teknopark Bulvari No:1/4A No:412 Pendik / Istanbul /
TURKIYE
[image: LinkedIn icon]
<https://www.linkedin.com/in/davuthan-yaman-185b0b65/>

Bu e-posta'nin icerdigi bilgiler, ekleri de dahil olmak uzere KISIYE ÖZEL
ve hukuken gizlidir. Bu mesajin gonderilmek istendigi kisi degilseniz ya da
bu e-posta'yi yanlislikla aldiysaniz, lutfen yollayan kisiyi haberdar
ediniz ve mesaji bilgisayarinizdan siliniz. Mesajin iceriginden,
iletilmesinden, alinmasindan, saklanmasindan, gizliliginin korunamamasindan
ve dogacak baska herhangi bir sonuctan Endpoint Bilgi Teknolojileri
Güvenliği Ar-Ge A.Ş. ve istirakleri sorumlu tutulamaz.

This e-mail message including any attachment is confidential for
the intended recipient and legally privileged. If you are not the
intended recipient or you received this e-mail in error kindly notify the
sender and delete this message from your computer. Endpoint Bilgi
Teknolojileri Güvenliği Ar-Ge A.Ş. and subsidiaries shall have no liability
with regard to the information contained in the message, its transmission,
reception, storage, preservation of confidentiality and any other
consequences.


Pól <notifications@github.com>, 10 Şub 2020 Pzt, 14:35 tarihinde şunu yazdı:

**Pull request closed without merging**
